language: node_js
sudo: false
node_js:
- '10'
- '12'
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  api_key:
    secure: c5QfuJnDzR5TH0ti4E+ebNSC7mhvuCiKSZ8YP0XamYWucUIckGvVG4VffYt8Lk1Z+OnoHXdrKO6D9zKvsMdOrjI8Khu9C0vsIpLxDr3wcPUlv7ejsIxkj/cnpdAolaWdN6wbPZSLZrSBlHRaToxMXxIOPwbl2b4/efSvkK61k40Ll1NAHyM53xo42v3dYAprm7vA8j8BEnAjEcm+peH+bfWgtxYa3CvnFYMmvedn9von0veo8/3DWQID/FesyKrqcrVmGHqTHVp0OI9iiE/8dEe8Z1ACtc2/lfZkAj8uX5GEm9yGXl58ropiJG1af1DL3pUhNLhkXiA07bnxxJFe4oLt1zk8H6zs/Xc+PNTJ3b8QzESWsliA+uxvNGAq3od4TbyWwe1nQ76WZ86pe77HNnA56+xhtgt4gppf7rr/nLUJ+yTXQGjLVTDclogmrp4L/o4nFHvUwjGS1pNDY6ZM3eWcly5SjWCq3Ix6rcOIXUW3GrGboITu/qocpFyzxH+9vn9AZ00JoNgghXBbmgLOZr1otvRvpvmP85yyEqr7RY0/wWU3Oe42Fa/eW/gk1ZhvgDk/3Bte/NaSKQINUcO8EVuWagu4jq+sjymNS3HwDNSfJ6XDdoADqOlFUf28ZL9JhahwDB1aDFHTLsXe0TVfm1sJ1sC5dTkdkrio/jBUr94=
  on:
    tags: true
    repo: mozilla/eslint-config-amo
